### PR TITLE
Implement markdown writer command

### PR DESCRIPTION
**Pull request by julianprester**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #7 (just for tracking)

## What is the new behavior?

I followed the excellent documentation to create a WriterCommand for a simple markdown writer

- Markdown writer outputs simple markdown formatted string
- Uses document name as header
- Formats highlights as blockquotes
- Highlight page can be added at the end of the blockquote with an option
- Added tests (first time writing Python tests 🙈, feedback appreciated)

Here's what I've managed to come up with. Let me know what you think.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Thank you for this amazing project. This is what I was missing from my remarkable workflow 😊

@sabidib

### CODE REVIEW

**Comment by sabidib** [comment]
Thank you for the contribution @julianprester. A quick skim didn't show any obvious red flags, I'll take a closer look later today.

**Review by sabidib — CHANGES_REQUESTED** [review]
Seems like the auto-linter did not run. I ran scripts/linting locally and found a few warnings that isort and autopep8 should have fixed.

Otherwise, the code and tests look great!

I left a few questions and comments, once those are addressed and the auto-linter is run I'll take another look and 🚢

**Comment by julianprester** [comment]
Thanks a lot for your comments @sabidib. I've got everything set up properly now and learned a ton in the process 😉
I think I've addressed your feedback above. Let me know what you think.

**Comment by ismaild** [comment]
What can be done to merge this? I started developing a markdown writer. Luckily i decided to check if there was PR first to see if anyone had done a similar thing.

**Pull request closed without merging**
